name: Release Docker Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: '镜像标签,留空则使用 package.json 中的版本号。务必注意:请确认选择了正确的分支。完整输入示例:3.0.11-rc0 '
        required: true
        default: ''
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

env:
  repo_name_android: "siyuan-android"
  repo_name: "siyuan"
  repo_owner: "dockers-x"
  package_json: "app/package.json"
  docker_hub_owner: ${{ secrets.DOCKER_HUB_USER }}
  docker_hub_repo: "siyuan"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}
          submodules: recursive

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version ${{ env.package_json }} -r"

      - name: Set image tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.image_tag }}" != "" ]]; then
            IMAGE_TAG="v${{ github.event.inputs.image_tag }}"
          else
            IMAGE_TAG="v${{ steps.version.outputs.value }}"
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Building with tag: ${IMAGE_TAG}"

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
          buildkitd-flags: |
            --allow-insecure-entitlement security.insecure
            --allow-insecure-entitlement network.host

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        run: |
          IMAGE_TAG="${{ steps.tag.outputs.IMAGE_TAG }}"
          
          echo "Building multi-arch image with tag: $IMAGE_TAG"
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ env.docker_hub_owner }}/${{ env.docker_hub_repo }}:${IMAGE_TAG} \
            --tag ${{ env.docker_hub_owner }}/${{ env.docker_hub_repo }}:latest \
            --tag ghcr.io/${{ github.repository_owner }}/${{ env.docker_hub_repo }}:${IMAGE_TAG} \
            --tag ghcr.io/${{ github.repository_owner }}/${{ env.docker_hub_repo }}:latest \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            .


      - name: Verify multi-arch build
        run: |
          IMAGE_TAG="${{ steps.tag.outputs.IMAGE_TAG }}"
          echo "Verifying multi-arch manifest for ${{ env.docker_hub_owner }}/${{ env.docker_hub_repo }}:${IMAGE_TAG}"
          docker buildx imagetools inspect ${{ env.docker_hub_owner }}/${{ env.docker_hub_repo }}:${IMAGE_TAG}
